import { useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { showToast } from '@/components/ui/Toast';
import { APP_NAME, APP_TAGLINE } from '@/lib/constants';
import { Truck, ArrowRight, ArrowLeft, Shield } from 'lucide-react';

const DEMO_OTP='123456';
const VEHICLES=['تریلی','جفت','تک','کامیونت و خاور','وانت و نیسان'];
const BODIES=['روباز','مسقف','یخچال','کمپرسی'];
const BODY_FEATURES=['بغل بازشو','معمولی','چادری','فلزی'];
const PLATE_LETTERS=['ب','پ','ت','ث','ج','چ','ح','خ','د','ذ','ر','ز','ژ','س','ش','ص','ض','ط','ظ','ع','غ','ف','ق','ک','گ','ل','م','ن','و','ه','ی'];
const fa=(v:string)=>v.replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[Number(d)]||d);
const en=(v:string)=>v.replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d)));
type Step='details'|'otp'|'vehicleType'|'bodyType'|'feature'|'plate';

export function AuthPage({mode,onModeChange}:{mode:'login'|'register';onModeChange:(mode:'login'|'register')=>void}){
 const {signIn,signUp}=useAuth();
 const [step,setStep]=useState<Step>('details');
 const [fullName,setFullName]=useState(''); const [phone,setPhone]=useState(''); const [otp,setOtp]=useState(''); const [loading,setLoading]=useState(false); const [errors,setErrors]=useState<Record<string,string>>({});
 const [vehicle,setVehicle]=useState({vehicleType:'',bodyType:'',bodyFeature:'',p1:'',letter:'',p2:'',iran:''});
 const normalizedPhone=en(phone.trim());
 const reset=()=>{setStep('details');setOtp('');setErrors({});setLoading(false)};
 const sendOtp=()=>{const e:Record<string,string>={};if(mode==='register'&&!fullName.trim())e.fullName='نام و نام خانوادگی الزامی است';if(!/^09\d{9}$/.test(normalizedPhone))e.phone='شماره موبایل معتبر نیست';setErrors(e);if(Object.keys(e).length)return;setStep('otp');showToast(`کد تأیید آزمایشی: ${DEMO_OTP}`,'success')};
 const finishLogin=async()=>{setLoading(true);const r=await signIn(normalizedPhone);if(r.error){showToast(r.error,'error');setLoading(false)}else showToast('با موفقیت وارد شدید','success')};
 const handleOtp=(v:string)=>{const n=en(v).replace(/\D/g,'').slice(0,6);setOtp(n);if(n.length===6){if(n===DEMO_OTP){setTimeout(()=>mode==='register'?setStep('vehicleType'):finishLogin(),100)}else setErrors({otp:'کد تأیید صحیح نیست'})}};
 const finishRegister=async()=>{if(!vehicle.vehicleType||!vehicle.bodyType||!vehicle.p1||!vehicle.letter||!vehicle.p2||!vehicle.iran){setErrors({vehicle:'اطلاعات خودرو و پلاک را کامل کنید'});return}setLoading(true);const r=await signUp(normalizedPhone,'driver',fullName.trim());if(r.error){showToast(r.error,'error');setLoading(false);return}const id=JSON.parse(localStorage.getItem('bbberah-demo-current')||'null');if(id)localStorage.setItem(`bbberah-fleet-${id}`,JSON.stringify({...vehicle,plateNumber:`${vehicle.p1}${vehicle.letter}${vehicle.p2} ایران ${vehicle.iran}`}));showToast('حساب راننده با موفقیت ایجاد شد','success')};
 const back=()=>{if(step==='otp')setStep('details');else if(step==='vehicleType')setStep('otp');else if(step==='bodyType')setStep('vehicleType');else if(step==='feature')setStep('bodyType');else if(step==='plate'){if(['روباز','مسقف'].includes(vehicle.bodyType))setStep('feature');else setStep('bodyType')}};
 const selectBody=(x:string)=>{setVehicle(v=>({...v,bodyType:x,bodyFeature:['روباز','مسقف'].includes(x)?v.bodyFeature:''}));setStep(['روباز','مسقف'].includes(x)?'feature':'plate')};
 return <div dir="rtl" className="min-h-screen bg-gradient-to-b from-orange-50 to-white flex flex-col"><div className="flex-1 flex flex-col justify-center px-5 py-8 max-w-md mx-auto w-full"><div className="text-center mb-7"><div className="mx-auto w-16 h-16 rounded-[22px] bg-primary-600 text-white flex items-center justify-center shadow-xl shadow-primary-600/20"><Truck className="w-8 h-8"/></div><h1 className="text-2xl font-black text-gray-900 mt-3">{APP_NAME}</h1><p className="text-sm text-gray-400 mt-1">اپلیکیشن رانندگان · {APP_TAGLINE}</p></div>
 <div className="flex gap-1 bg-gray-100 rounded-xl p-1 mb-5"><button onClick={()=>{onModeChange('login');reset()}} className={`flex-1 py-3 rounded-lg font-bold ${mode==='login'?'bg-white text-primary-700 shadow-sm':'text-gray-500'}`}>ورود</button><button onClick={()=>{onModeChange('register');reset()}} className={`flex-1 py-3 rounded-lg font-bold ${mode==='register'?'bg-white text-primary-700 shadow-sm':'text-gray-500'}`}>ثبت‌نام</button></div>
 {mode==='login'&&step==='details'?<div className="space-y-4"><h2 className="text-xl font-black">ورود راننده</h2><p className="text-sm text-gray-400">ورود فقط با شماره موبایل و کد تأیید انجام می‌شود.</p><Input label="شماره موبایل" value={phone} onChange={e=>setPhone(en(e.target.value))} placeholder="09123456789" type="tel" dir="ltr" error={errors.phone}/><Button type="button" size="full" onClick={sendOtp}>دریافت کد تأیید <ArrowLeft className="w-4 h-4 mr-2"/></Button></div>:
 <div className="space-y-4">{step!=='details'&&<button onClick={back} className="flex items-center gap-2 text-sm text-gray-500 font-bold"><ArrowRight className="w-4 h-4"/> برگشت</button>}
 {step==='details'&&<><h2 className="text-xl font-black">ثبت‌نام راننده</h2><p className="text-sm text-gray-400">برای ساخت حساب راننده، ابتدا نام و شماره موبایل را ثبت کنید.</p><Input label="نام و نام خانوادگی" value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="مثال: علی محمدی" error={errors.fullName}/><Input label="شماره موبایل" value={phone} onChange={e=>setPhone(en(e.target.value))} placeholder="09123456789" type="tel" dir="ltr" error={errors.phone}/><Button type="button" size="full" onClick={sendOtp}>دریافت کد تأیید <ArrowLeft className="w-4 h-4 mr-2"/></Button></>}
 {step==='otp'&&<><h2 className="text-xl font-black">تأیید شماره موبایل</h2><p className="text-sm text-gray-400">کد ۶ رقمی ارسال‌شده به {normalizedPhone}</p><Input label="کد تأیید" value={fa(otp)} onChange={e=>handleOtp(e.target.value)} placeholder="۱۲۳۴۵۶" inputMode="numeric" dir="ltr" error={errors.otp} autoFocus/><p className="text-xs text-gray-400">کد آزمایشی: ۱۲۳۴۵۶ — با ورود رقم ششم ادامه می‌دهد.</p></>}
 {step==='vehicleType'&&<><h2 className="text-xl font-black">۱. انتخاب نوع کامیون</h2><p className="text-sm text-gray-400">نوع وسیله نقلیه خود را انتخاب کنید.</p><div className="grid grid-cols-1 gap-3">{VEHICLES.map(x=><button type="button" key={x} onClick={()=>{setVehicle(v=>({...v,vehicleType:x}));setStep('bodyType')}} className={`p-4 rounded-2xl border-2 text-right font-black bg-white ${vehicle.vehicleType===x?'border-primary-500 bg-orange-50 text-primary-700':'border-gray-100'}`}>{x}<ArrowLeft className="w-4 h-4 inline mr-2"/></button>)}</div></>}
 {step==='bodyType'&&<><h2 className="text-xl font-black">۲. انتخاب نوع بارگیر</h2><p className="text-sm text-gray-400">نوع بارگیر را انتخاب کنید.</p><div className="grid grid-cols-2 gap-3">{BODIES.map(x=><button type="button" key={x} onClick={()=>selectBody(x)} className={`p-4 rounded-2xl border-2 font-black ${vehicle.bodyType===x?'border-primary-500 bg-orange-50 text-primary-700':'border-gray-100 bg-white'}`}>{x}</button>)}</div></>}
 {step==='feature'&&<><h2 className="text-xl font-black">۳. ویژگی بارگیر</h2><p className="text-sm text-gray-400">برای بارگیر {vehicle.bodyType} ویژگی مناسب را انتخاب کنید.</p><div className="grid grid-cols-2 gap-3">{BODY_FEATURES.map(x=><button type="button" key={x} onClick={()=>{setVehicle(v=>({...v,bodyFeature:x}));setStep('plate')}} className={`p-4 rounded-2xl border-2 font-black ${vehicle.bodyFeature===x?'border-primary-500 bg-orange-50 text-primary-700':'border-gray-100 bg-white'}`}>{x}</button>)}</div></>}
 {step==='plate'&&<><h2 className="text-xl font-black">۴. ثبت پلاک</h2><p className="text-sm text-gray-400">پلاک را دقیقاً مطابق پلاک خودرو وارد کنید.</p><div className="rounded-2xl border-4 border-gray-300 bg-white overflow-hidden shadow-inner"><div className="flex items-stretch min-h-[78px]" dir="ltr"><input value={fa(vehicle.p1)} onChange={e=>setVehicle(v=>({...v,p1:en(e.target.value).replace(/\D/g,'').slice(0,2)}))} inputMode="numeric" placeholder="__" className="w-[24%] text-center text-2xl font-black outline-none"/><select value={vehicle.letter} onChange={e=>setVehicle(v=>({...v,letter:e.target.value}))} className="w-[22%] border-x border-gray-300 bg-white text-center text-2xl font-black outline-none"><option value="">حرف</option>{PLATE_LETTERS.map(x=><option key={x} value={x}>{x}</option>)}</select><input value={fa(vehicle.p2)} onChange={e=>setVehicle(v=>({...v,p2:en(e.target.value).replace(/\D/g,'').slice(0,3)}))} inputMode="numeric" placeholder="___" className="w-[32%] text-center text-2xl font-black outline-none"/><div className="w-[22%] border-r border-gray-300 flex flex-col items-center justify-center text-[10px] font-bold text-gray-500"><span>IRAN</span><b className="text-lg">{fa(vehicle.iran||'')}</b></div></div></div><Input label="کد ایران" value={fa(vehicle.iran)} onChange={e=>setVehicle(v=>({...v,iran:en(e.target.value).replace(/\D/g,'').slice(0,2)}))} placeholder="__" inputMode="numeric" dir="ltr" error={errors.vehicle}/><Button type="button" size="full" loading={loading} onClick={finishRegister}>تکمیل ثبت‌نام و ورود</Button></>}
 </div>}
 <div className="mt-6 flex items-center justify-center gap-2 text-xs text-gray-300"><Shield className="w-3.5 h-3.5"/> ورود شما تا زمان خروج از حساب حفظ می‌شود</div></div></div>;
}
