import { useMemo, useState } from 'react';
import { AuthPage } from '@/pages/auth/AuthPage';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/Button';
import { Card, CardBody } from '@/components/ui/Card';
import { ArrowLeft, ChevronLeft, LogOut, MapPin, Phone, Search, User, Navigation, PackageSearch, PhoneCall, CarFront, WalletCards, ReceiptText, SunMoon, Headphones, FileText } from 'lucide-react';

type Page='home'|'profile'|'account'|'vehicle'|'wallet'|'transactions'|'display'|'support'|'rules'|'search'|'nearby'|'calls';
type Load={id:string;ownerId:string;title:string;from:string;to:string;type:string;vehicle:string;weight:number;price:number;pickup:string;delivery:string;status:string;originLat?:number;originLng?:number};
const LOADS_KEY='bbberah-demo-loads';
const seedLoads:Load[]=[
{id:'l1',ownerId:'seed',title:'بار خشک تهران به مشهد',from:'تهران',to:'مشهد',type:'بار خشک',vehicle:'تریلی',weight:18000,price:24500000,pickup:'امروز، ۱۴:۳۰',delivery:'فردا، ۱۰:۰۰',status:'open',originLat:35.6892,originLng:51.3890},
{id:'l2',ownerId:'seed',title:'مواد غذایی کرج به اصفهان',from:'کرج',to:'اصفهان',type:'مواد غذایی',vehicle:'کامیون',weight:9000,price:12800000,pickup:'فردا، ۰۸:۰۰',delivery:'فردا، ۲۰:۰۰',status:'open',originLat:35.8400,originLng:50.9391},
{id:'l3',ownerId:'seed',title:'کالای تجاری تبریز به تهران',from:'تبریز',to:'تهران',type:'کالای تجاری',vehicle:'خاور',weight:4500,price:8600000,pickup:'فردا، ۱۱:۳۰',delivery:'پس‌فردا، ۰۹:۰۰',status:'open',originLat:38.0962,originLng:46.2738},
{id:'l4',ownerId:'seed',title:'مصالح ساختمانی قم به تهران',from:'قم',to:'تهران',type:'ساختمانی',vehicle:'تریلی',weight:22000,price:16400000,pickup:'شنبه، ۰۷:۰۰',delivery:'شنبه، ۱۳:۰۰',status:'open',originLat:34.6416,originLng:50.8746},
{id:'l5',ownerId:'seed',title:'بار کشاورزی رشت به قزوین',from:'رشت',to:'قزوین',type:'کشاورزی',vehicle:'کامیون',weight:7500,price:9700000,pickup:'شنبه، ۰۹:۰۰',delivery:'شنبه، ۱۶:۰۰',status:'open',originLat:37.2808,originLng:49.5832},
];
const provinces:{name:string;cities:string[]}[]=[
{name:'آذربایجان شرقی',cities:['تبریز','مراغه','مرند','اهر','میانه','بناب','شبستر','سراب','جلفا','اسکو','هشترود','بستان‌آباد','کلیبر','آذرشهر','عجب‌شیر','ملکان','ورزقان']},
{name:'آذربایجان غربی',cities:['ارومیه','خوی','مهاباد','بوکان','میاندوآب','سلماس','نقده','پیرانشهر','سردشت','ماکو','شاهین‌شهر','تکاب','اشنویه','چایپاره']},
{name:'اردبیل',cities:['اردبیل','مشگین‌شهر','پارس‌آباد','خلخال','گرمی','نمین','نیر','بیله‌سوار','کوثر']},
{name:'اصفهان',cities:['اصفهان','کاشان','خمینی‌شهر','نجف‌آباد','شاهین‌شهر','فلاورجان','مبارکه','شهرضا','گلپایگان','سمیرم','آران و بیدگل','نائین','نطنز','داران','فریدونشهر']},
{name:'البرز',cities:['کرج','نظرآباد','هشتگرد','طالقان','اشتهارد','محمدشهر','فردیس']},
{name:'ایلام',cities:['ایلام','دهلران','مهران','آبدانان','دره‌شهر','ایوان','سرابله','موسیان']},
{name:'بوشهر',cities:['بوشهر','برازجان','کنگان','گناوه','دیر','دیلم','جم','عسلویه','خورموج']},
{name:'تهران',cities:['تهران','ری','شمیرانات','شهریار','اسلامشهر','قدس','ملارد','ورامین','پاکدشت','دماوند','فیروزکوه','رباط‌کریم','پردیس','پیشوا']},
{name:'چهارمحال و بختیاری',cities:['شهرکرد','بروجن','فارسان','لردگان','اردل','سامان','کوهرنگ','کیار']},
{name:'خراسان جنوبی',cities:['بیرجند','قائن','طبس','فردوس','نهبندان','سربیشه','درمیان','سرایان','خوسف']},
{name:'خراسان رضوی',cities:['مشهد','نیشابور','سبزوار','تربت حیدریه','تربت جام','قوچان','کاشمر','گناباد','تایباد','چناران','فریمان','درگز','خواف','بردسکن','سرخس']},
{name:'خراسان شمالی',cities:['بجنورد','شیروان','اسفراین','جاجرم','آشخانه','فاروج','گرمه','راز و جرگلان']},
{name:'خوزستان',cities:['اهواز','دزفول','آبادان','خرمشهر','بندر ماهشهر','اندیمشک','شوش','شوشتر','بهبهان','ایذه','مسجدسلیمان','رامهرمز','شادگان','سوسنگرد','هندیجان','لالی']},
{name:'زنجان',cities:['زنجان','ابهر','خرمدره','قیدار','ماه‌نشان','طارم','سلطانیه']},
{name:'سمنان',cities:['سمنان','شاهرود','دامغان','گرمسار','مهدی‌شهر','آرادان','میامی']},
{name:'سیستان و بلوچستان',cities:['زاهدان','چابهار','زابل','ایرانشهر','سراوان','خاش','کنارک','نیک‌شهر','راسک','میرجاوه','زهک']},
{name:'فارس',cities:['شیراز','مرودشت','جهرم','فسا','کازرون','لار','آباده','داراب','فیروزآباد','نی‌ریز','ممسنی','لامرد','اقلید','استهبان','سپیدان','گراش']},
{name:'قزوین',cities:['قزوین','تاکستان','آبیک','الوند','بوئین‌زهرا','آوج']},
{name:'قم',cities:['قم','جعفریه','کهک','سلفچگان']},
{name:'کردستان',cities:['سنندج','سقز','مریوان','بانه','قروه','کامیاران','بیجار','دیواندره','دهگلان']},
{name:'کرمان',cities:['کرمان','رفسنجان','سیرجان','جیرفت','بم','زرند','راور','کهنوج','بردسیر','شهربابک','بافت','عنبرآباد','رودبار جنوب']},
{name:'کرمانشاه',cities:['کرمانشاه','اسلام‌آباد غرب','سنقر','کنگاور','هرسین','صحنه','جوانرود','پاوه','سرپل ذهاب','قصرشیرین','گیلانغرب','روانسر']},
{name:'کهگیلویه و بویراحمد',cities:['یاسوج','گچساران','دهدشت','دوگنبدان','لیکک','سی‌سخت']},
{name:'گلستان',cities:['گرگان','گنبد کاووس','علی‌آباد کتول','آق‌قلا','بندر ترکمن','کردکوی','مینودشت','کلاله','آزادشهر','رامیان','گمیشان']},
{name:'گیلان',cities:['رشت','انزلی','لاهیجان','لنگرود','رودسر','آستارا','تالش','فومن','صومعه‌سرا','رودبار','آستانه اشرفیه','ماسال','شفت']},
{name:'لرستان',cities:['خرم‌آباد','بروجرد','دورود','الیگودرز','کوهدشت','نورآباد','الشتر','پلدختر','ازنا','دلفان']},
{name:'مازندران',cities:['ساری','بابل','آمل','قائمشهر','نوشهر','چالوس','تنکابن','رامسر','بهشهر','نکا','بابلسر','محمودآباد','جویبار','فریدونکنار','نور','کلاردشت']},
{name:'مرکزی',cities:['اراک','ساوه','خمین','محلات','دلیجان','شازند','تفرش','آشتیان','زرندیه']},
{name:'هرمزگان',cities:['بندرعباس','قشم','کیش','میناب','بندر لنگه','رودان','حاجی‌آباد','پارسیان','جاسک','سیریک','بستک']},
{name:'همدان',cities:['همدان','ملایر','نهاوند','تویسرکان','کبودرآهنگ','رزن','اسدآباد','فامنین']},
{name:'یزد',cities:['یزد','میبد','اردکان','بافق','مهریز','اشکذر','تفت','ابرکوه','خاتم']},
];
const allCities=provinces.flatMap(p=>p.cities.map(city=>({city,province:p.name})));
const fa=(v:string)=>v.replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[Number(d)]||d);const money=(v:number)=>new Intl.NumberFormat('fa-IR').format(v);
function loadData(){try{const v=JSON.parse(localStorage.getItem(LOADS_KEY)||'null');return Array.isArray(v)?v:seedLoads}catch{return seedLoads}}
function distanceKm(aLat:number,aLng:number,bLat:number,bLng:number){const r=6371,dLat=(bLat-aLat)*Math.PI/180,dLng=(bLng-aLng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(aLat*Math.PI/180)*Math.cos(bLat*Math.PI/180)*Math.sin(dLng/2)**2;return r*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function CityPicker({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){const [open,setOpen]=useState(false);const [q,setQ]=useState('');const results=useMemo(()=>{const s=q.trim();if(!s)return provinces.slice(0,8).flatMap(p=>p.cities.slice(0,3).map(city=>({city,province:p.name})));return allCities.filter(x=>x.city.includes(s)||x.province.includes(s)).slice(0,30)},[q]);return <div className="relative"><button type="button" onClick={()=>setOpen(!open)} className="w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 text-right flex items-center justify-between"><span className={value?'font-bold text-gray-900':'text-gray-400'}>{value||placeholder}</span><ChevronLeft className="w-4 h-4 text-gray-400"/></button>{open&&<div className="absolute z-30 top-full mt-2 w-full rounded-2xl border border-gray-200 bg-white shadow-xl p-3"><div className="relative"><Search className="absolute right-3 top-3 w-4 h-4 text-gray-400"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجوی شهر یا استان" className="w-full rounded-xl bg-gray-50 pr-10 pl-3 py-3 outline-none"/></div><div className="max-h-64 overflow-auto mt-2 space-y-1">{results.map(x=><button key={`${x.province}-${x.city}`} type="button" onClick={()=>{onChange(x.city);setOpen(false);setQ('')}} className="w-full text-right rounded-xl px-3 py-2 hover:bg-orange-50"><b>{x.city}</b><span className="text-xs text-gray-400 mr-2">{x.province}</span></button>)}</div></div>}</div>}
function LoadList({loads,onCall}:{loads:Load[];onCall:(l:Load)=>void}){return <div className="space-y-3">{loads.length?loads.map(l=><Card key={l.id}><CardBody className="p-4"><div className="flex justify-between gap-3"><div><span className="text-xs font-bold text-primary-700 bg-primary-50 rounded-lg px-2 py-1">{l.type}</span><h3 className="font-black mt-2">{l.title}</h3></div><b className="text-primary-700 whitespace-nowrap">{money(l.price)} تومان</b></div><div className="flex items-center gap-3 mt-4"><div className="flex-1"><b>{l.from}</b><span className="block text-xs text-gray-400">مبدأ</span></div><ArrowLeft className="w-5 h-5 text-primary-500"/><div className="flex-1"><b>{l.to}</b><span className="block text-xs text-gray-400">مقصد</span></div></div><div className="grid grid-cols-2 gap-2 mt-4 text-xs"><div className="rounded-xl bg-gray-50 p-2"><span className="text-gray-400">وسیله</span><b className="block mt-1">{l.vehicle}</b></div><div className="rounded-xl bg-gray-50 p-2"><span className="text-gray-400">وزن</span><b className="block mt-1">{fa(String(l.weight))} کیلو</b></div></div><Button className="w-full mt-3" onClick={()=>onCall(l)}><Phone className="w-4 h-4"/> درخواست تماس</Button></CardBody></Card>):<div className="text-center py-16 text-gray-400">باری مطابق جستجوی شما پیدا نشد.</div>}</div>}
export default function App(){const {session,profile,loading,signOut}=useAuth();const [authMode,setAuthMode]=useState<'login'|'register'>('login');const [page,setPage]=useState<Page>('home');const [loads]=useState<Load[]>(loadData);const [destination,setDestination]=useState('');const [search,setSearch]=useState('');const [gps,setGps]=useState<{lat:number;lng:number}|null>(null);const [message,setMessage]=useState('');const [profileName,setProfileName]=useState(profile?.full_name||'');
if(loading)return <div className="min-h-screen flex items-center justify-center font-black text-primary-600">در حال بارگذاری براه...</div>;if(!session||!profile)return <AuthPage mode={authMode} onModeChange={setAuthMode}/>;
const own=loads.filter(l=>l.ownerId===profile.id);const available=loads.filter(l=>l.ownerId!==profile.id&&l.status==='open');const searchLoads=available.filter(l=>(!search||`${l.title} ${l.from} ${l.to} ${l.type} ${l.vehicle}`.includes(search))&&(!destination||l.to.includes(destination)||l.from.includes(destination)));const nearby=available.filter(l=>!gps||!l.originLat||!l.originLng||distanceKm(gps.lat,gps.lng,l.originLat,l.originLng)<=150);const gpsClick=()=>{if(!navigator.geolocation){setMessage('GPS در این مرورگر در دسترس نیست.');return}navigator.geolocation.getCurrentPosition(p=>{setGps({lat:p.coords.latitude,lng:p.coords.longitude});setMessage('بارهای اطراف شما به‌روزرسانی شد.')},()=>setMessage('دسترسی به موقعیت مکانی فعال نیست.'))};const go=(p:Page)=>{setPage(p);setMessage('')};
const title={home:'براه',profile:'حساب کاربری',account:'اطلاعات حساب کاربری',vehicle:'خودروی من',wallet:'کیف پول',transactions:'تراکنش ها',display:'حالت نمایش',support:'پشتیبانی',rules:'قوانین و مقررات',search:'جستجوی بار',nearby:'اطراف من',calls:'تماس‌های من'}[page];
const profileItems=[
{page:'account' as Page,icon:User,title:'اطلاعات حساب کاربری',text:'نام، شماره تلفن و اطلاعات حساب'},
{page:'vehicle' as Page,icon:CarFront,title:'خودروی من',text:'مشخصات خودرو و بارگیر'},
{page:'wallet' as Page,icon:WalletCards,title:'کیف پول',text:'موجودی و اعتبار حساب'},
{page:'transactions' as Page,icon:ReceiptText,title:'تراکنش ها',text:'سوابق و جزئیات تراکنش‌ها'},
{page:'display' as Page,icon:SunMoon,title:'حالت نمایش',text:'تنظیم ظاهر برنامه'},
{page:'support' as Page,icon:Headphones,title:'پشتیبانی',text:'ارتباط با پشتیبانی براه'},
{page:'rules' as Page,icon:FileText,title:'قوانین و مقررات',text:'قوانین استفاده از براه'},
];
const sectionBack=()=>go('profile');
return <div dir="rtl" className="min-h-screen bg-gray-50"><header className="sticky top-0 z-20 bg-white/95 backdrop-blur border-b border-gray-100"><div className="max-w-lg mx-auto px-4 py-4 relative flex items-center justify-center"><button type="button" onClick={()=>page==='profile'||page==='home'?go('home'):sectionBack()} aria-label="بازگشت" className="absolute left-4 top-1/2 -translate-y-1/2 w-10 h-10 rounded-xl bg-gray-50 border border-gray-200 flex items-center justify-center text-gray-700"><ArrowLeft className="w-5 h-5"/></button><h1 className="text-2xl font-black tracking-tight">{title}</h1></div></header><main className="max-w-lg mx-auto px-4 py-5 pb-10">{message&&<div className="mb-4 rounded-xl bg-emerald-50 text-emerald-700 px-4 py-3 text-sm font-bold">{message}</div>}
{page==='home'&&<div className="space-y-5"><div className="grid grid-cols-2 gap-4"><button onClick={()=>go('nearby')} className="aspect-square rounded-3xl bg-white border border-gray-100 shadow-sm p-5 text-right flex flex-col justify-between hover:shadow-md transition-shadow"><Navigation className="w-7 h-7 text-primary-600"/><b className="text-lg">اطراف من</b><span className="text-xs text-gray-400">بارهای نزدیک به شما</span></button><button onClick={()=>go('search')} className="aspect-square rounded-3xl bg-white border border-gray-100 shadow-sm p-5 text-right flex flex-col justify-between hover:shadow-md transition-shadow"><PackageSearch className="w-7 h-7 text-primary-600"/><b className="text-lg">جستجوی بار</b><span className="text-xs text-gray-400">پیدا کردن بار مناسب</span></button><button onClick={()=>go('calls')} className="aspect-square rounded-3xl bg-white border border-gray-100 shadow-sm p-5 text-right flex flex-col justify-between hover:shadow-md transition-shadow"><PhoneCall className="w-7 h-7 text-primary-600"/><b className="text-lg">تماس‌های من</b><span className="text-xs text-gray-400">پیگیری درخواست‌ها</span></button><button onClick={()=>go('profile')} className="aspect-square rounded-3xl bg-white border border-gray-100 shadow-sm p-5 text-right flex flex-col justify-between hover:shadow-md transition-shadow"><User className="w-7 h-7 text-primary-600"/><b className="text-lg">حساب کاربری</b><span className="text-xs text-gray-400">اطلاعات حساب و خودرو</span></button></div></div>}
{page==='profile'&&<div className="space-y-3">{profileItems.map((item,index)=><button key={item.page} onClick={()=>go(item.page)} className="w-full flex items-center gap-4 rounded-2xl bg-white border border-gray-100 shadow-sm px-4 py-4 text-right hover:shadow-md transition-shadow"><div className="w-11 h-11 shrink-0 rounded-xl bg-primary-50 flex items-center justify-center"><item.icon className="w-5 h-5 text-primary-700"/></div><div className="min-w-0 flex-1"><b className="block text-[15px]">{item.title}</b><span className="block text-xs text-gray-400 mt-1">{item.text}</span></div><ChevronLeft className="w-5 h-5 text-gray-300 shrink-0"/></button>)}<Button variant="outline" className="w-full mt-3" onClick={signOut}><LogOut className="w-4 h-4"/> خروج از حساب</Button></div>}
{page==='account'&&<div className="space-y-4"><Card><CardBody className="p-5 space-y-4"><div className="flex items-center gap-4"><div className="w-14 h-14 rounded-2xl bg-primary-50 flex items-center justify-center"><User className="w-7 h-7 text-primary-700"/></div><div><h2 className="font-black text-lg">اطلاعات حساب کاربری</h2><p className="text-sm text-gray-400" dir="ltr">{profile.phone}</p></div></div><input value={profileName} onChange={e=>setProfileName(e.target.value)} className="w-full rounded-xl border border-gray-200 px-4 py-3" placeholder="نام و نام خانوادگی"/><div className="rounded-xl bg-gray-50 px-4 py-3 text-sm">بارهای ثبت‌شده توسط شما: <b>{fa(String(own.length))}</b></div></CardBody></Card></div>}
{page==='vehicle'&&<div className="space-y-4"><Card><CardBody className="p-5 space-y-4"><div className="flex items-center gap-3"><CarFront className="w-6 h-6 text-primary-600"/><div><h2 className="font-black">خودروی من</h2><p className="text-xs text-gray-400 mt-1">مشخصات خودروی ثبت‌شده</p></div></div><div className="rounded-xl bg-gray-50 p-4"><b>خودرو</b><p className="text-sm text-gray-500 mt-1">هنوز خودرویی ثبت نشده است.</p></div><Button className="w-full" onClick={()=>setMessage('بخش ثبت و ویرایش خودرو آماده شد.')}>ثبت یا ویرایش خودرو</Button></CardBody></Card></div>}
{page==='wallet'&&<div className="space-y-4"><Card><CardBody className="p-6 text-center"><WalletCards className="w-8 h-8 mx-auto text-primary-600"/><p className="text-sm text-gray-400 mt-3">موجودی کیف پول</p><div className="text-3xl font-black mt-2">۰ تومان</div><Button className="w-full mt-5" onClick={()=>setMessage('امکان افزایش موجودی در نسخه بعدی فعال می‌شود.')}>افزایش موجودی</Button></CardBody></Card></div>}
{page==='transactions'&&<div className="space-y-3"><Card><CardBody className="p-5 text-center"><ReceiptText className="w-8 h-8 mx-auto text-primary-600"/><h2 className="font-black mt-3">تراکنش ها</h2><p className="text-sm text-gray-400 mt-2">هنوز تراکنشی ثبت نشده است.</p></CardBody></Card></div>}
{page==='display'&&<div className="space-y-3"><button onClick={()=>setMessage('حالت نمایش روشن انتخاب شد.')} className="w-full rounded-2xl bg-white border border-gray-100 px-5 py-4 flex items-center justify-between text-right"><span><b>روشن</b><span className="block text-xs text-gray-400 mt-1">نمایش روشن برنامه</span></span><SunMoon className="w-5 h-5 text-primary-600"/></button><button onClick={()=>setMessage('حالت نمایش خودکار انتخاب شد.')} className="w-full rounded-2xl bg-white border border-gray-100 px-5 py-4 flex items-center justify-between text-right"><span><b>خودکار</b><span className="block text-xs text-gray-400 mt-1">مطابق تنظیمات دستگاه</span></span><SunMoon className="w-5 h-5 text-primary-600"/></button></div>}
{page==='support'&&<div className="space-y-4"><Card><CardBody className="p-5"><Headphones className="w-7 h-7 text-primary-600"/><h2 className="font-black mt-3">پشتیبانی براه</h2><p className="text-sm text-gray-500 mt-2 leading-7">برای پیگیری مشکل یا دریافت راهنمایی با پشتیبانی تماس بگیرید.</p><a href="tel:02100000000" className="mt-4 w-full rounded-xl bg-primary-600 text-white py-3 flex items-center justify-center gap-2 font-bold"><Phone className="w-4 h-4"/> تماس با پشتیبانی</a></CardBody></Card></div>}
{page==='rules'&&<div className="space-y-4"><Card><CardBody className="p-5 leading-8 text-sm text-gray-600"><h2 className="font-black text-lg text-gray-900 mb-3">قوانین و مقررات</h2><p>استفاده از براه به معنی پذیرش قوانین و مقررات سرویس است.</p><p className="mt-3">کاربر مسئول صحت اطلاعات حساب، خودرو و درخواست‌های ثبت‌شده خود است.</p><p className="mt-3">استفاده از خدمات باید مطابق قوانین حمل‌ونقل و مقررات جاری انجام شود.</p></CardBody></Card></div>}
{page==='search'&&<div className="space-y-4"><div className="relative"><Search className="absolute right-4 top-3.5 w-5 h-5 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} className="w-full rounded-2xl border border-gray-200 bg-white pr-12 pl-4 py-3.5" placeholder="جستجوی بار"/></div><CityPicker value={destination} onChange={setDestination} placeholder="مقصد: همه شهرها"/><Button variant="outline" className="w-full" onClick={()=>setDestination('')}>همه شهرها</Button><LoadList loads={searchLoads} onCall={()=>{setMessage('درخواست تماس برای این بار ثبت شد.');go('calls')}}/></div>}
{page==='nearby'&&<div className="space-y-4"><Card><CardBody className="p-5"><div className="flex items-center gap-3"><MapPin className="w-6 h-6 text-primary-600"/><div><b>اطراف من</b><p className="text-xs text-gray-400 mt-1">بارهای نزدیک به موقعیت فعلی</p></div></div><Button className="w-full mt-4" onClick={gpsClick}>دریافت موقعیت من</Button></CardBody></Card><LoadList loads={nearby} onCall={()=>{setMessage('درخواست تماس برای این بار ثبت شد.');go('calls')}}/></div>}
{page==='calls'&&<div className="space-y-3">{searchLoads.slice(0,5).map(l=><Card key={l.id}><CardBody className="p-4 flex items-center justify-between"><div><b>{l.title}</b><p className="text-xs text-gray-400 mt-1">درخواست تماس ثبت شده</p></div><a href={`tel:${profile.phone||''}`} className="w-11 h-11 rounded-xl bg-primary-50 text-primary-700 flex items-center justify-center"><Phone className="w-5 h-5"/></a></CardBody></Card>)}{!searchLoads.length&&<div className="text-center py-16 text-gray-400">هنوز تماسی ثبت نشده است.</div>}</div>}
</main></div>;
}